import 'package:api_app/api_result.dart';
import 'package:api_app/network_exceptions.dart';
import 'package:api_app/user.dart';
import 'package:api_app/web_services.dart';

class MyRepo {
final WebServices webServices;

MyRepo(this.webServices);

Future <ApiResult<List<User>>> getAllUsers() async {
try {
var response=await webServices.getAllUsers();
  return ApiResult.success(response);
}catch(error){
  return ApiResult.failure(NetworkExceptions.getDioException(error));

}
}


/* var response = await webServices.getAllUsers();


return response.map((singleUserDataFromJson) => User.fromJson(singleUserDataFromJson.toJson())).toList(); //is already generated by retrofit in web_services.g.dart
}*/

//dont need to make anthor class to get one user


Future<User> getUserById(int userId) async {
var response = await webServices.getUserById(userId);

return User.fromJson(response.toJson());
}

/* Future<User> createNewUser(User newUser) async {
return await webServices.createNewUser(
  newUser,' Bearer a5207bde3b5d7dbbb41bcc8a025264f2fab475f5dfdbc1f682375edbf8d8566a');  
}  */

Future <ApiResult<User>> createNewUser(User newUser) async{
try {
  var response=await webServices.createNewUser(
 newUser,'Bearer a5207bde3b5d7dbbb41bcc8a025264f2fab475f5dfdbc1f682375edbf8d8566a' 
);
  return ApiResult.success(response);
}catch(error){
  return ApiResult.failure(NetworkExceptions.getDioException(error));
}
}


Future<dynamic> deleteUser(String id) async {
return await webServices.deleteUser(
  id,' Bearer a5207bde3b5d7dbbb41bcc8a025264f2fab475f5dfdbc1f682375edbf8d8566a');

}

}
