import 'package:json_annotation/json_annotation.dart';
part 'user.g.dart';    // JOSN_srializable file auto generated by build_runner packege

@JsonSerializable()
class User {

  int? id;
  String? name;
  String? email;
  String? gender;
  String? status;

  User({this.id, this.name, this.email, this.gender, this.status});

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  
  Map<String, dynamic> toJson() => _$UserToJson(this);

}